INSERT INTO AREA (ID, NAME, DESCRIPTION, ACREAGE) VALUES (1, 'Gondor', 'Southern Númenórean realm in exile.', 1000.44);
INSERT INTO AREA (ID, NAME, DESCRIPTION, ACREAGE) VALUES (2, 'Mordor', 'Base of operations of Sauron.', 1200.88);
ALTER TABLE AREA ALTER COLUMN ID RESTART WITH 3;

INSERT INTO CREATURE (ID, NAME, HEIGHT, WEIGHT, AGILITY) VALUES (1, 'Orc', 150, 60, 20);
INSERT INTO CREATURE (ID, NAME, HEIGHT, WEIGHT, AGILITY) VALUES (2, 'Balrog', 300, 3500, 5);
ALTER TABLE CREATURE ALTER COLUMN ID RESTART WITH 3;

INSERT INTO WEAPON (ID, NAME, GUNREACH, AMMUNITION) VALUES (1, 'Bow', 40, 'Fire arrow');
INSERT INTO WEAPON (ID, NAME, GUNREACH, AMMUNITION) VALUES (2, 'Catapult', 25, 'Rock');
ALTER TABLE WEAPON ALTER COLUMN ID RESTART WITH 3;

INSERT INTO HUNTINGEXPERIENCE (ID, WEAPON_ID, CREATURE_ID, DATEOFEXPERIENCE, EFFICIENCY, DESCRIPTION) VALUES (1, 1, 1, '2010-11-22', 50, 'Direct to head.');
INSERT INTO HUNTINGEXPERIENCE (ID, WEAPON_ID, CREATURE_ID, DATEOFEXPERIENCE, EFFICIENCY, DESCRIPTION) VALUES (2, 1, 2, '2010-11-23', 0, 'It is resist.');
ALTER TABLE HUNTINGEXPERIENCE ALTER COLUMN ID RESTART WITH 3;

INSERT INTO CREATURE_AREA (CREATURE_ID, AREA_ID) VALUES (2, 2);
INSERT INTO CREATURE_AREA (CREATURE_ID, AREA_ID) VALUES (1, 1);